
set -a terminal-features "tmux-256color:rgb"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g mouse on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"
set -g status-right ""
set -g status-left "#S"
set -g status-interval 5
set -g focus-events on
set -g history-limit 50000

bind f run "tmux neww ~/.local/bin/tmux-session-dispensary"
bind p run "tmux display-popup -E -w 60% -h 60% -d ~ zsh"
bind b set -g status
bind E show-environment -g
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi Enter send -X copy-selection
bind r source-file "~/.config/tmux/tmux.conf"
bind s choose-tree -Zs

# pane navigation with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing with vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# better splits
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v
bind = select-layout tiled

# kill pane without confirmation
bind x kill-pane

# kill all windows except the current one
bind o kill-window -a
